name: Deploy on GitHub Pages

on:
  push:
    branches:
    - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Yarn install
      uses: borales/actions-yarn@master
      with:
        args: install
    - name: Yarn build
      uses: borales/actions-yarn@master
      with:
        args: build:prod
    - name: Deploy
      uses: maxheld83/ghpages@master
      env:
        BUILD_DIR: dist/
        GH_PAT: ${{ secrets.GH_PAT }}
