on: push
name: Deploy on GitHub Pages
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Filters for GitHub Actions
      uses: actions/bin/filter@master
      with:
        args: branch master
    - name: Yarn install
      uses: borales/actions-yarn@master
      with:
        args: install
    - name: Yarn build
      uses: borales/actions-yarn@master
      with:
        args: build:prod
    - name: Deploy
      uses: maxheld83/ghpages@master
      env:
        BUILD_DIR: dist/
        GH_PAT: ${{ secrets.GH_PAT }}
